services:
  - type: web
    name: n8n
    env: docker
    plan: starter
    buildCommand: docker pull n8nio/n8n:latest
    startCommand: docker run -p $PORT:5678 --name n8n n8nio/n8n n8n start --tunnel
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 10
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        sync: false
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false
      
      - key: WEBHOOK_TUNNEL_URL
        fromService:
          type: web
          name: n8n
          property: url
      - key: N8N_WEBHOOK_TUNNEL_URL
        fromService:
          type: web
          name: n8n
          property: url
      
      - key: N8N_PORT
        value: "5678"
      - key: PORT
        value: "5678"
      - key: N8N_PROTOCOL
        value: "https"
      - key: N8N_ENCRYPTION_KEY
        generateValue: true