services:
  - type: web
    name: n8n
    env: docker
    plan: starter
    healthCheckPath: /
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        sync: false
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false
      - key: N8N_HOST
        fromService:
          type: web
          name: n8n
          property: host
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: n8n
          property: host
      - key: N8N_WEBHOOK_URL
        fromService:
          type: web
          name: n8n
          property: host
      - key: N8N_WEBHOOK_TEST_URL
        fromService:
          type: web
          name: n8n
          property: host
      - key: N8N_PORT
        value: "5678"
      - key: PORT
        value: "5678"
      - key: N8N_PROTOCOL
        value: "https"
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 10