services:
  - type: web
    name: postgresql
    env: docker
    plan: starter
    dockerCommand: postgres
    envVars:
      - key: POSTGRES_DB
        value: n8n
      - key: POSTGRES_USER
        value: n8nuser
      - key: POSTGRES_PASSWORD
        generateValue: true
    disk:
      name: postgres-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 10

  - type: web
    name: n8n
    env: docker
    plan: starter
    dockerCommand: n8n start
    healthCheckPath: /
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        generateValue: true
      - key: N8N_PROTOCOL
        value: "https"
      - key: N8N_PORT
        value: "5678"
      - key: PORT
        value: "5678"
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: postgresql-c61q.onrender.com
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        value: n8n
      - key: DB_POSTGRESDB_USER
        value: n8nuser
      - key: DB_POSTGRESDB_PASSWORD
        value: "Herb$2009$"
    disk:
      name: n8n-data
      mountPath: /data
      sizeGB: 10