services:
  - type: web
    name: n8n
    env: docker
    plan: starter
    healthCheckPath: /healthz
    healthCheckTimeout: 300
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        sync: false
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false

      - key: N8N_WEBHOOK_URL
        value: "https://${RENDER_EXTERNAL_URL}"
      - key: N8N_WEBHOOK_TEST_URL
        value: "https://${RENDER_EXTERNAL_URL}"
      - key: WEBHOOK_URL
        value: "https://${RENDER_EXTERNAL_URL}"
      - key: N8N_HOST
        value: "${RENDER_EXTERNAL_HOSTNAME}"

      - key: N8N_PROTOCOL
        value: "https"
      - key: N8N_PORT
        value: "5678"
      - key: PORT
        value: "5678"
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: N8N_USER_FOLDER
        value: "/data"

    disk:
      name: n8n-data
      mountPath: /data
      sizeGB: 10